module.exports = {
  // Get expenses list
  GET_EXPENSES: 'GET_EXPENSES',
  GET_EXPENSES_SUCCESS: 'GET_EXPENSES_SUCCESS',
  GET_EXPENSES_ERROR: 'GET_EXPENSES_ERROR',

  // Add Expense
  ADD_EXPENSE: 'ADD_EXPENSE',
  ADD_EXPENSE_SUCCESS: 'ADD_EXPENSE_SUCCESS',
  ADD_EXPENSE_ERROR: 'ADD_EXPENSE_ERROR',

  // Add Expense By Filter
  GET_EXPENSES_BY_FILTER: 'GET_EXPENSES_BY_FILTER',
  GET_EXPENSES_BY_FILTER_SUCCESS: 'GET_EXPENSES_BY_FILTER_SUCCESS',
  GET_EXPENSES_BY_FILTER_ERROR: 'GET_EXPENSES_BY_FILTER_ERROR'

};
